// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/andrewhowdencom/prst/internal/app"
	"github.com/andrewhowdencom/prst/internal/commands"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

// NewApplication constructs the cobra.Command application graph.
func NewApplication() *cobra.Command {
	v := commands.NewCommands()
	command := app.NewRootCommand(v)
	return command
}
